### 가축 추가 POST
POST http://localhost:5000/cattle/register
Content-Type: application/json

{
  "cattleId": "C110",
  "birthdate": "2019-12-31",
  "gender": "female",
  "weight": "111",
  "dad": "C52",
  "mom": "C76",
  "owner": "farmer1" 
}

### 유저 가축 조회 POST
POST http://localhost:5000/cattle/findcattle
Content-Type: application/json

{
  "cattleId": "C110",
  "owner": "farmer1" 
}
